# Use root/example as user/password credentials
version: '3.1'

services:

    theapp:
        image: vlad/theapp
        depends_on:
         - "mysql"
         - "redis"
         - "postgres"

    mysql:
        image: mysql:5.5
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example

    redis:
        image: redis
        restart: always

    postgres:
        image: postgres
        restart: always

