# Use root/example as user/password credentials
version: '3.1'

services:

    theapp:
        image: vlad/theapp
        environment:
            WAIT_FOR_MySQL: "Server = mysql; Port=3306; Uid = root; Pwd = example; Connect Timeout = 5"
            WAIT_FOR_MySQL_2: "Server = mysql_another; Port=3306; Uid = root; Pwd = example; Connect Timeout = 5"
            WAIT_FOR_PostgreSQL: "Host = postgres; Port=5432; User ID=postgres; Password=postgres; Database=postgres; Timeout = 5"
            WAIT_FOR_MongoDB: "mongodb://mongodb:27017"
            WAIT_FOR_RabbitMQ: "amqp://rabbitmq:5672"
            WAIT_FOR_Redis: "redis:6379"
            WAIT_FOR_Redis: "redis_another:6379"
            WAIT_FOR_MSSQL: "Data Source=sqlserver; User ID=sa; Password=~1qazxsw2; Timeout = 5"
            WAIT_FOR_HttpGet_google: "https://google.com"
            WAIT_FOR_HttpGet_google_404: "https://google.com/404"
            WAIT_FOR_Ping_nginx1: "nginx1"
            WAIT_FOR_Ping_nginx2: "nginx2"
            WAIT_FOR_HttpGet_nginx1: "http://nginx1"
            WAIT_FOR_HttpGet_nginx2: "http://nginx2"
            WAIT_FOR_Ping_google: "google.com"
            WAIT_FOR_Ping_sqlserver: "sqlserver"
            WAIT_FOR_Ping_redis: "redis"
            WAIT_FOR_Ping_mongodb: "mongodb"
            WAIT_FOR_Ping_mysql1: "mysql"
            WAIT_FOR_Ping_mysql2: "mysql_another"
        depends_on:
         - "mysql"
         - "redis"
         - "postgres"
         - "mongodb"
         - "rabbitmq"
         - "sqlserver"
#        links:
#         - "mysql"
#         - "redis"
#         - "postgres"
#         - "mongodb"
#         - "rabbitmq"
#         - "sqlserver"

    mysql:
        image: mysql:5.5
        restart: "no"
        environment:
            MYSQL_ROOT_PASSWORD: example
        ports:
        - "3306:3306"

    mysql_another:
        image: mysql:5.6
        restart: "no"
        environment:
            MYSQL_ROOT_PASSWORD: example
        ports:
        - "3306:3306"

    redis:
        image: redis
        restart: "no"
        ports:
        - "6379:6379"

    redis_another:
        image: redis:3.2
        restart: "no"
        ports:
        - "6379:6379"

    postgres:
        image: postgres:9.4
        restart: "no"
        environment:
            POSTGRES_PASSWORD: postgres
        ports:
        - "5432"

    mongodb:
        image: mongo:3.4
        restart: "no"
        ports:
        - "27017"

    rabbitmq:
        image: rabbitmq:3.4
        restart: "no"
        ports:
        - "5672"

    sqlserver:
        image: microsoft/mssql-server-linux
        restart: "no"
        environment:
            ACCEPT_EULA: Y 
            SA_PASSWORD: ~1qazxsw2
            MSSQL_PID: Developer
        ports:
        - "1433"

    nginx1:
        image: nginx
        ports:
        - "8091:80"
        command: [nginx-debug, '-g', 'daemon off;']

    nginx2:
        image: nginx
        ports:
        - "8092:80"
        command: [nginx-debug, '-g', 'daemon off;']
