# Use root/example as user/password credentials
version: '3.1'

services:

    theapp:
        image: vlad/theapp
        environment:
            WAIT_FOR_MySQL_42: "Server = mysql; Port=3306; Uid = root; Pwd = example; Connect Timeout = 5"
            WAIT_FOR_PostgreSQL: "Host = postgres; Port=5432; User ID=postgres; Password=postgres; Database=postgres; Timeout = 5"
            WAIT_FOR_MongoDB_42: "mongodb://mongodb:27017"
            WAIT_FOR_RabbitMQ_42: "amqp://rabbitmq:5672"
            WAIT_FOR_Redis_42: "redis:6379"
            WAIT_FOR_MSSQL_42: "Data Source=sqlserver; User ID=sa; Password=~1qazxsw2; Timeout = 5"
        depends_on:
         - "mysql"
         - "redis"
         - "postgres"
         - "mongodb"
         - "rabbitmq"
         - "sqlserver"
        links:
         - "mysql"
         - "redis"
         - "postgres"
         - "mongodb"
         - "rabbitmq"
         - "sqlserver"

    mysql:
        image: mysql:5.5
        restart: "no"
        environment:
            MYSQL_ROOT_PASSWORD: example
        ports:
        - "3306"

    redis:
        image: redis
        restart: "no"
        ports:
        - "6379"

    postgres:
        image: postgres:9.4
        restart: "no"
        environment:
            POSTGRES_PASSWORD: postgres
        ports:
        - "5432"

    mongodb:
        image: mongo:3.4
        restart: "no"
        ports:
        - "27017"

    rabbitmq:
        image: rabbitmq:3.2
        restart: "no"
        ports:
        - "5672"

    sqlserver:
        image: microsoft/mssql-server-linux
        restart: "no"
        environment:
            ACCEPT_EULA: Y 
            SA_PASSWORD: ~1qazxsw2
            MSSQL_PID: Developer
        ports:
        - "1433"
