# Use root/example as user/password credentials
version: '3.1'

services:

    theapp:
        image: vlad/theapp
        depends_on:
         - "mysql"
         - "redis"
         - "postgres"
         - "mongodb"
         - "rabbitmq"
         - "sqlserver"
        links:
         - sqlserver

    mysql:
        image: mysql:5.5
        restart: "no"
        environment:
            MYSQL_ROOT_PASSWORD: example
        ports:
        - "3306"

    redis:
        image: redis
        restart: "no"
        ports:
        - "6379"

    postgres:
        image: postgres:9.4
        restart: "no"
        environment:
            POSTGRES_PASSWORD: postgres
        ports:
        - "5432"

    postgres101:
        image: postgres:9.6
        restart: "no"
        environment:
            POSTGRES_PASSWORD: postgres
        ports:
        - "15432:5432"

    mongodb:
        image: mongo:3.4
        restart: "no"
        ports:
        - "27017"

    rabbitmq:
        image: rabbitmq:3.6
        restart: "no"
        ports:
        - "5672"

    sqlserver:
        image: microsoft/mssql-server-linux
        restart: "no"
        environment:
            ACCEPT_EULA: Y 
            SA_PASSWORD: ~1qazxsw2
            MSSQL_PID: Developer
        ports:
        - "1433"
