sudo: required
services:
  - docker
language: csharp
mono: none
dotnet: 2.0.3
dist: trusty
script:
 - docker info; printf "\n\n\n"; docker-compose version; printf "\n\n\n"
 - cd TheApp;
 - bash patch-build-date.sh
 - dotnet publish -v:m -c Release -r linux-x64 -o bin/linux TheApp.sln
 - cd bin/linux
 - ./WaitFor -Timeout=5 -Ping=google.com -Ping=google.com42 -HttpGet=http://google.com -HttpGet=http://google.com/404
 - cp ../../../container/* .
 - docker build -t vlad/theapp .
 - export COMPOSE_HTTP_TIMEOUT=61
 - time (docker-compose create) 
 - docker-compose up -d
 - (docker kill lab_theapp_1 >/dev/null || true); docker start -i linux_theapp_1;
 - (docker kill lab_theapp_1 >/dev/null || true); docker start -i linux_theapp_1;
 - # docker-compose -f stack.yml down
