language: minimal
os: linux
dist: xenial
sudo: required
services:
  # - docker
mono: none
# dotnet: 2.2
env:
  global:
  - secure: none

install:
  - |
     sudo apt-get update \
          && sudo apt-get install apt-transport-https ca-certificates curl software-properties-common -y \
          && (curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - ) \
          && sudo apt-key fingerprint 0EBFCD88 \
          && sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \
          && sudo apt-get update \
          && sudo apt-get install docker-ce -y

  - apt-cache policy docker-ce
  - docker --version; docker-compose --version
  - export DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1; export DOTNET_CLI_TELEMETRY_OPTOUT=1;
  # - url=https://raw.githubusercontent.com/devizer/glist/master/install-dotnet-and-nodejs.sh; (wget -q -nv --no-check-certificate -O - $url 2>/dev/null || curl -ksSL $url) | bash -s dotnet
  - |
        time (curl -ksSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin -c 2.2 -i ~/net)
        export PATH="$HOME/net:$PATH"



script:
    - time dotnet restore --disable-parallel 
    - cd compose && bash -e compose-up.sh

cache:
  directories:
    - '/home/travis/.local/share/NuGet/v3-cache/'
