sudo: required
services:
  - docker
language: csharp
mono: none
dotnet: 2.0.3
env:
  global:
    secure: C/kKH2Ad7t0v0n62mBYkplfMFKHnqZ8RzOZH6KnA7O/CxwdS1O5KyRRiSWF609PESbkQBDOmV26qmtJOZoVEhgcwF3NQ0c7lgW8M2gNYKlEzAMLCigsRdfjx+x83uFyKhe/XXq4wGncGC6alanY/FNqsCZwv8BRD3VfIZDXMT6Wbd5JV$
dist: trusty
script:
 - printenv | sort
 - docker info; printf "\n\n\n"; docker-compose version; printf "\n\n\n"
 - cd TheApp;
 - bash patch-build-date.sh
 - dotnet publish -v:m -c Release -r linux-x64 -o bin/linux TheApp.sln
 - cd bin/linux
 - ./WaitFor -Timeout=5 -Ping=google.com -Ping=google.com42 -HttpGet=http://google.com -HttpGet=http://google.com/404
 - cp ../../../container/* .
 - docker build -t lab/theapp .
 - export COMPOSE_HTTP_TIMEOUT=61
 - export COMPOSE_PROJECT_NAME=lab
 - time (docker-compose create) 
 - docker-compose up -d
 - (docker kill lab_theapp_1 >/dev/null || true); docker start -i lab_theapp_1;
 - (docker kill lab_theapp_1 >/dev/null || true); docker start -i lab_theapp_1;
 - # docker-compose -f stack.yml down
